"""The tool manifest: which tools this server must offer, and their contract.

``tools.json`` is generated by ``scripts/generate-manifest.mjs`` from the
Homedata Developer Playground catalogue and must not be edited by hand.
``descriptions.json`` and ``param_descriptions.json`` are the hand-written
descriptions shown to MCP clients.
"""

from __future__ import annotations

import json
from functools import cache
from importlib import resources
from typing import Any


@cache
def load_manifest() -> dict[str, Any]:
    return json.loads(resources.files(__package__).joinpath("tools.json").read_text("utf-8"))


@cache
def load_param_descriptions() -> dict[str, dict[str, str]]:
    return json.loads(resources.files(__package__).joinpath("param_descriptions.json").read_text("utf-8"))


@cache
def load_descriptions() -> dict[str, str]:
    return json.loads(resources.files(__package__).joinpath("descriptions.json").read_text("utf-8"))
