#!/usr/bin/env python3
"""Has the Playground catalogue moved since tools.json was generated?

thor, which holds the catalogue, is private, so CI cannot regenerate the
manifest. thor publishes the same catalogue as the "api-surface" block of
https://homedata.co.uk/llms-full.txt, generated by its sync-try-catalogue.mjs.
This script parses that block's self-serve section and compares each
endpoint's method, path and token price with homedata_mcp/manifest/tools.json.

    python scripts/check_drift.py                    # fetch the live file
    python scripts/check_drift.py --file llms-full.txt

Exit 0: in step. Exit 1: drift, regenerate the manifest (see the generator).
Exit 2: the file could not be fetched or its format is not understood. Not a
verdict either way.

WHAT THIS DOES NOT COVER:
  - Parameters. The public block lists param names loosely; tools.json takes
    them from the catalogue source, which this cannot see.
  - Price rules the public block does not state. It states risks' `all` price
    and that property custom adds add-ons; add-on prices themselves, and any
    other parameter-dependent price, are invisible here.
  - Enterprise and on-request products. They are skipped by design: they sit
    under the "### Enterprise" heading and are never offered as tools.
  - The flood layer family (/risks/flood/{layer}/). The public block documents
    it as its own entry, but the Playground offers it only through risks.
  - Whether loki serves any of it. This compares two descriptions of the offer.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from collections import Counter
from pathlib import Path

LIVE_URL = "https://homedata.co.uk/llms-full.txt"
MANIFEST = Path(__file__).resolve().parent.parent / "homedata_mcp" / "manifest" / "tools.json"

BLOCK = re.compile(
    r"<!-- BEGIN GENERATED: api-surface \(source_hash: (?P<hash>[0-9a-f]{64})\).*?-->(?P<body>.*?)<!-- END GENERATED: api-surface -->",
    re.DOTALL,
)
HEADER = re.compile(r"^\*\*(?P<method>GET|POST|PUT|PATCH|DELETE) (?P<path>/\S*)\*\*(?P<rest>.*)$")
ENTERPRISE_HEADING = re.compile(r"^### Enterprise\b")
# Entries the public block documents separately but the Playground offers through another endpoint.
KNOWN_EXTRA_ENTRIES = {("GET", "/risks/flood/{layer}/"): "flood layers are reached through risks (risk_type flood:<layer>)"}

WEIGHTS = (
    (re.compile(r"^free\b"), lambda m: (0, False, None)),
    (re.compile(r"^(\d+) tokens? for the base record plus"), lambda m: (int(m[1]), True, None)),
    (re.compile(r"^(\d+) tokens? per hazard or flood layer; `all` is (\d+) tokens?$"), lambda m: (int(m[1]), False, int(m[2]))),
    (re.compile(r"^(\d+) tokens?$"), lambda m: (int(m[1]), False, None)),
)


class FormatError(Exception):
    """The file is not in the shape this parser understands."""


def parse_surface(text: str) -> tuple[str, Counter]:
    """Return (source_hash, Counter of (method, path, price signature))."""
    block = BLOCK.search(text)
    if not block:
        raise FormatError("no api-surface block with a source_hash")
    entries: Counter = Counter()
    current: tuple[str, str] | None = None
    for line in block["body"].splitlines():
        if ENTERPRISE_HEADING.match(line):
            break
        header = HEADER.match(line)
        if header:
            if current:
                raise FormatError(f"{current[0]} {current[1]} has no Weight line")
            key = (header["method"], header["path"])
            current = None if key in KNOWN_EXTRA_ENTRIES else key
            continue
        if current and line.startswith("- Weight: "):
            weight = line[len("- Weight: "):].strip()
            for pattern, signature in WEIGHTS:
                m = pattern.match(weight)
                if m:
                    entries[(*current, signature(m))] += 1
                    break
            else:
                raise FormatError(f"unrecognised weight for {current[0]} {current[1]}: {weight!r}")
            current = None
    if current:
        raise FormatError(f"{current[0]} {current[1]} has no Weight line")
    if not entries:
        raise FormatError("no self-serve endpoints found")
    return block["hash"], entries


def manifest_entries(manifest: dict) -> Counter:
    entries: Counter = Counter()
    for tool in manifest["tools"]:
        tokens = tool["tokens"]
        all_price = next((w["tokens"] for w in tokens.get("when", []) if w["param"] == "risk_type" and "all" in w["in"]), None)
        entries[(tool["method"], tool["path"], (tokens["default"], bool(tokens.get("plus_with_addons")), all_price))] += 1
    return entries


def describe(entry) -> str:
    method, path, (price, addons, all_price) = entry
    extra = " plus add-ons" if addons else f", all={all_price}" if all_price is not None else ""
    return f"{method} {path} ({price} tokens{extra})"


def compare(manifest: dict, text: str) -> tuple[list[str], str | None]:
    """Return (drift lines, note). Raises FormatError."""
    source_hash, public = parse_surface(text)
    ours = manifest_entries(manifest)
    drift = [f"in the public catalogue, not in tools.json: {describe(e)}" for e in sorted((public - ours).elements())]
    drift += [f"in tools.json, not in the public catalogue: {describe(e)}" for e in sorted((ours - public).elements())]
    recorded = manifest["source"].get("llms_full_api_surface_source_hash")
    note = None if recorded == source_hash else (
        f"source_hash changed ({recorded} -> {source_hash}); it covers labels and copy too, so this alone is not drift"
    )
    return drift, note


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compare tools.json with the public Playground catalogue.")
    parser.add_argument("--file", help="read llms-full.txt from a file instead of fetching it")
    parser.add_argument("--url", default=LIVE_URL)
    parser.add_argument("--manifest", default=str(MANIFEST))
    args = parser.parse_args(argv)

    try:
        if args.file:
            text = Path(args.file).read_text(encoding="utf-8")
        else:
            req = urllib.request.Request(args.url, headers={"User-Agent": "homedata-mcp-drift-check"})
            with urllib.request.urlopen(req, timeout=30) as resp:
                text = resp.read().decode("utf-8")
        manifest = json.loads(Path(args.manifest).read_text(encoding="utf-8"))
        drift, note = compare(manifest, text)
    except (OSError, FormatError, ValueError) as exc:
        print(f"could not check drift: {exc}", file=sys.stderr)
        return 2

    if note:
        print(note)
    if drift:
        print("\n".join(drift))
        print(f"DRIFT: {len(drift)} difference(s). Regenerate: node scripts/generate-manifest.mjs --thor <thor clone>")
        return 1
    print(f"in step: {sum(manifest_entries(manifest).values())} tools match the public Playground catalogue")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
